const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const os = require('os');

const transcript = require('../transcript.js');

function tmpProjects() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ckproj-'));
  process.env.CK_PROJECTS_DIR = dir;
  return dir;
}
function writeJsonl(dir, name, lines) {
  const p = path.join(dir, name);
  fs.writeFileSync(p, lines.map(l => JSON.stringify(l)).join('\n') + '\n');
  return p;
}
const userText = (text, extra) => ({ type: 'user', timestamp: '2026-07-11T10:00:00.000Z', message: { role: 'user', content: text }, ...extra });
const asstBlocks = (blocks, extra) => ({ type: 'assistant', timestamp: '2026-07-11T10:00:01.000Z', message: { role: 'assistant', content: blocks }, ...extra });
const toolResultLine = (id, isErr) => ({ type: 'user', timestamp: '2026-07-11T10:00:02.000Z', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: id, content: 'big output', is_error: !!isErr }] } });

test('text turns + merge: claude blocks across lines and around tool results form ONE turn', () => {
  const dir = tmpProjects();
  const p = writeJsonl(dir, 's.jsonl', [
    userText('hello there'),
    asstBlocks([{ type: 'text', text: 'working on it' }]),
    asstBlocks([{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'ls', description: 'List files' } }]),
    toolResultLine('t1', false),
    asstBlocks([{ type: 'text', text: 'done!' }]),
  ]);
  const turns = transcript.parseTranscript(p);
  assert.strictEqual(turns.length, 2);
  assert.strictEqual(turns[0].role, 'you');
  assert.strictEqual(turns[0].blocks[0].text, 'hello there');
  assert.strictEqual(turns[1].role, 'claude');
  assert.deepStrictEqual(turns[1].blocks.map(b => b.type), ['text', 'tool', 'text']);
  assert.strictEqual(turns[1].blocks[1].name, 'Bash');
  assert.strictEqual(turns[1].blocks[1].label, 'List files'); // description preferred over command
  assert.strictEqual(turns[1].blocks[1].status, 'done');      // paired with its tool_result
});

test('tool status: is_error -> error; unpaired in final turn -> running; unpaired earlier -> done', () => {
  const dir = tmpProjects();
  const p = writeJsonl(dir, 's.jsonl', [
    asstBlocks([{ type: 'tool_use', id: 'a', name: 'Edit', input: { file_path: '/x.js' } }]), // unpaired, not final
    toolResultLine('zzz', false), // unrelated result (skipped as a turn, harvested as status)
    userText('and then?'),
    asstBlocks([{ type: 'tool_use', id: 'b', name: 'Bash', input: { command: 'rm x' } }]),    // error result
    toolResultLine('b', true),
    asstBlocks([{ type: 'tool_use', id: 'c', name: 'Read', input: { file_path: '/y.js' } }]), // unpaired, final turn
  ]);
  const turns = transcript.parseTranscript(p);
  const flat = turns.flatMap(t => t.blocks).filter(b => b.type === 'tool');
  assert.deepStrictEqual(flat.map(b => b.status), ['done', 'error', 'running']);
});

test('skips synthetic turns (isMeta / isCompactSummary / isSidechain), thinking, tool_result, wrapper tags, interrupt marker', () => {
  const dir = tmpProjects();
  const p = writeJsonl(dir, 's.jsonl', [
    { type: 'mode', mode: 'normal' },
    userText('<system-reminder>injected</system-reminder>'),
    userText('<bash-input>vercel whoami</bash-input>'),          // a `!command` echo — no isMeta flag
    userText('<bash-stdout>omar@falaq</bash-stdout>'),
    userText('Caveat: The messages below were generated by the user while running local commands. blah'),
    userText('[Request interrupted by user]'),
    userText('Base directory for this skill: /x\nENTIRE SKILL WALL', { isMeta: true }),           // Skill-tool injection
    userText('This session is being continued from a previous conversation…', { isCompactSummary: true }),
    userText('real question'),
    asstBlocks([{ type: 'thinking', thinking: 'private' }, { type: 'text', text: 'answer' }]),
    asstBlocks([{ type: 'text', text: 'sidechain noise' }], { isSidechain: true }),
    toolResultLine('nope', false),
  ]);
  const turns = transcript.parseTranscript(p);
  assert.strictEqual(turns.length, 2);
  assert.strictEqual(turns[0].blocks[0].text, 'real question');
  assert.deepStrictEqual(turns[1].blocks, [{ type: 'text', text: 'answer' }]);
});

test('narrowed harness filter PRESERVES a real user message that merely starts with < or Caveat', () => {
  const dir = tmpProjects();
  const p = writeJsonl(dir, 's.jsonl', [
    userText('<3 this feature'),
    userText('<div class="x">a pasted snippet</div>'),
    userText('Caveat: my own note about the task'),
  ]);
  const turns = transcript.parseTranscript(p);
  assert.strictEqual(turns.length, 1); // three consecutive 'you' lines merge into one turn
  assert.deepStrictEqual(turns[0].blocks.map(b => b.text),
    ['<3 this feature', '<div class="x">a pasted snippet</div>', 'Caveat: my own note about the task']);
});

test('caps: maxTurns tail, maxText, maxLabel, and readCap drops the partial first line', () => {
  const dir = tmpProjects();
  const many = [];
  for (let i = 0; i < 30; i++) { many.push(userText('q' + i)); many.push(asstBlocks([{ type: 'text', text: 'a' + i }])); }
  const pm = writeJsonl(dir, 'm.jsonl', many);
  const t = transcript.parseTranscript(pm, { maxTurns: 10 });
  assert.strictEqual(t.length, 10);
  assert.strictEqual(t[9].blocks[0].text, 'a29');

  const pl = writeJsonl(dir, 'l.jsonl', [
    userText('x'.repeat(50)),
    asstBlocks([{ type: 'tool_use', id: 'z', name: 'Bash', input: { description: 'y'.repeat(50) } }]),
  ]);
  const tl = transcript.parseTranscript(pl, { maxText: 10, maxLabel: 8 });
  assert.strictEqual(tl[0].blocks[0].text.length, 10);      // maxText caps a text block
  assert.strictEqual(tl[1].blocks[0].label.length, 8);      // maxLabel caps a tool label

  // readCap < file size forces a tail read: the partial first line is dropped, the tail is kept intact.
  const big = writeJsonl(dir, 'big.jsonl', [
    userText('FIRST-' + 'p'.repeat(300)),   // long, so the tail read starts deep inside it
    userText('SECOND-kept'),
    userText('THIRD-kept'),
  ]);
  const cap = JSON.stringify(userText('SECOND-kept')).length + JSON.stringify(userText('THIRD-kept')).length + 6;
  const allText = transcript.parseTranscript(big, { readCap: cap }).flatMap(x => x.blocks).map(b => b.text).join(' ');
  assert.ok(!/FIRST-/.test(allText), 'partial first line dropped');
  assert.ok(allText.includes('SECOND-kept') && allText.includes('THIRD-kept'), 'tail retained');
});

test('jail + garbage: foreign path -> [], garbled lines skipped, missing file -> []', () => {
  const dir = tmpProjects();
  fs.writeFileSync(path.join(dir, 'g.jsonl'), 'not json\n' + JSON.stringify(userText('ok')) + '\n{broken\n');
  assert.deepStrictEqual(transcript.parseTranscript('/etc/hosts'), []);
  assert.deepStrictEqual(transcript.parseTranscript(path.join(dir, 'missing.jsonl')), []);
  const turns = transcript.parseTranscript(path.join(dir, 'g.jsonl'));
  assert.strictEqual(turns.length, 1);
});

test('memo caches by stat identity, invalidates on touch, and evicts least-recently-used entries', () => {
  const dir = tmpProjects();
  const first = writeJsonl(dir, 'memo-0.jsonl', [userText('zero')]);
  const a = transcript.parseTranscript(first);
  assert.strictEqual(transcript.parseTranscript(first), a);

  const st = fs.statSync(first);
  fs.utimesSync(first, st.atime, new Date(st.mtimeMs + 2000));
  const touched = transcript.parseTranscript(first);
  assert.notStrictEqual(touched, a);

  for (let i = 1; i <= 32; i++) writeJsonl(dir, `memo-${i}.jsonl`, [userText(String(i))]);
  for (let i = 1; i <= 32; i++) transcript.parseTranscript(path.join(dir, `memo-${i}.jsonl`));
  assert.notStrictEqual(transcript.parseTranscript(first), touched);
});

test('recentTouchedFiles returns only recent completed mutating tool paths', () => {
  const dir = tmpProjects();
  const now = Date.parse('2026-07-11T10:30:00.000Z');
  const p = writeJsonl(dir, 'touches.jsonl', [
    asstBlocks([{ type: 'tool_use', id: 'edit', name: 'Edit', input: { file_path: 'src/api.js' } }]),
    toolResultLine('edit', false),
    asstBlocks([{ type: 'tool_use', id: 'read', name: 'Read', input: { file_path: 'src/other.js' } }]),
    toolResultLine('read', false),
    asstBlocks([{ type: 'tool_use', id: 'failed', name: 'Write', input: { file_path: 'src/bad.js' } }]),
    toolResultLine('failed', true),
  ]);
  assert.deepEqual(transcript.recentTouchedFiles(p, dir, { now, recentMs: 60 * 60 * 1000 }), [path.join(dir, 'src/api.js')]);
});

test('completedActions returns the last three actually completed tools', () => {
  const dir = tmpProjects();
  const p = writeJsonl(dir, 'actions.jsonl', [
    asstBlocks([{ type: 'tool_use', id: 'a', name: 'Read', input: { file_path: 'a.js' } }]), toolResultLine('a', false),
    asstBlocks([{ type: 'tool_use', id: 'b', name: 'Edit', input: { file_path: 'b.js' } }]), toolResultLine('b', false),
    asstBlocks([{ type: 'tool_use', id: 'c', name: 'Bash', input: { description: 'Run tests' } }]), toolResultLine('c', false),
    asstBlocks([{ type: 'tool_use', id: 'd', name: 'Write', input: { file_path: 'd.js' } }]), toolResultLine('d', true),
    asstBlocks([{ type: 'tool_use', id: 'e', name: 'Bash', input: { description: 'Check diff' } }]), toolResultLine('e', false),
  ]);
  assert.deepEqual(transcript.completedActions(p), [
    { name: 'Edit', label: 'b.js', ts: '2026-07-11T10:00:01.000Z' },
    { name: 'Bash', label: 'Run tests', ts: '2026-07-11T10:00:01.000Z' },
    { name: 'Bash', label: 'Check diff', ts: '2026-07-11T10:00:01.000Z' },
  ]);
});
